# Generated by Django 3.2.2 on 2021-05-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
                ('category', models.CharField(max_length=64)),
                ('picture', models.CharField(max_length=512)),
                ('expiration', models.DateTimeField()),
            ],
        ),
    ]
