# Generated by Django 3.2.2 on 2021-05-18 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='lister',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posting', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='winner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='winning', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchers', to='auctions.Listings'),
        ),
    ]
